name: build-test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn validate
      - run: yarn prepare

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
          - Leonardo
          - Raphael
          - Donatello
          - Michelangelo
    outputs:
      names: ${{steps.accumulate.outputs.names}}
    steps:
      - uses: actions/checkout@v2
      - id: accumulate
        uses: ./
        with:
          outputs: ${{steps.accumulate.outputs.names || ''}}
          key: names
          value: ${{matrix.name}}
